services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./web:/web

  collector:
    build:
      context: .
      dockerfile: docker/collector/Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/app
